### ISSUE TITLE
Cuz mick is bully me

### ISSUE THREAD

**Issue by iDevMC** [Ssmidge/Ssmidge#1]
ＷＨＹ ＹＯＵ ＣＯＰＩΞＤ ＭＹ ＧＩＴＨＵＢ ＰΛＧΞ ＢＲＵＨ ：（
###### no cool

**Comment by Ssmidge** [comment]
Wut

**Comment by alpharr** [comment]
lmao you did doe

**Comment by iDevMC** [comment]
> lmao you did doe

yessir lmao, also @ImUpdated is literally the same as @ImDeprecated (@Ssmidge)

**Comment by Ssmidge** [comment]
Stop bully me ;C xd
